/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e6e2dc",
        "primary": "#004527",
        "on-error-container": "#93000a",
        "surface-variant": "#e6e2dc",
        "surface-container": "#f1ede7",
        "outline-variant": "#bfc9bf",
        "surface-container-low": "#f7f3ed",
        "on-primary-container": "#92d5a9",
        "secondary-container": "#fe8265",
        "on-tertiary-container": "#b9cabd",
        "on-surface-variant": "#404942",
        "error": "#ba1a1a",
        "surface": "#fdf9f3",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-dim": "#ddd9d4",
        "on-secondary-fixed": "#3d0600",
        "secondary-fixed-dim": "#ffb4a3",
        "on-secondary-container": "#731b07",
        "on-surface": "#1c1c18",
        "on-tertiary-fixed-variant": "#3b4a40",
        "on-primary": "#ffffff",
        "tertiary": "#2f3f35",
        "surface-container-high": "#ebe8e2",
        "on-error": "#ffffff",
        "secondary": "#a23d26",
        "primary-fixed": "#aef2c4",
        "primary-container": "#1b5e3b",
        "surface-tint": "#296a46",
        "on-primary-fixed": "#002110",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d5e7d9",
        "inverse-primary": "#92d5a9",
        "tertiary-fixed-dim": "#b9cbbd",
        "inverse-on-surface": "#f4f0ea",
        "on-background": "#1c1c18",
        "secondary-fixed": "#ffdad2",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#085230",
        "on-secondary-fixed-variant": "#822611",
        "outline": "#707971",
        "primary-fixed-dim": "#92d5a9",
        "tertiary-container": "#46564b",
        "background": "#fdf9f3",
        "surface-bright": "#fdf9f3",
        "inverse-surface": "#31302d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "8px",
        xl: "10px",
        full: "9999px",
      },
      fontFamily: {
        "body-md": ["DM Sans", "sans-serif"],
        "label-sm": ["DM Sans", "sans-serif"],
        "headline-lg": ["Fraunces", "serif"],
        "headline-md": ["Fraunces", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "display-xl": ["Fraunces", "serif"],
      },
    },
  },
  plugins: [],
}
