/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#6B5100",
        "surface-container": "#f1ede7",
        "primary": "#7C5400",
        "secondary-container": "#fe8265",
        "primary-fixed": "#FFDEA0",
        "on-error": "#ffffff",
        "on-background": "#1c1c18",
        "secondary-fixed": "#ffdad2",
        "outline-variant": "#CFC6B4",
        "on-tertiary-fixed-variant": "#4A3800",
        "on-primary-fixed": "#271900",
        "background": "#fdf9f3",
        "tertiary": "#4A3800",
        "surface-container-highest": "#e6e2dc",
        "inverse-on-surface": "#f4f0ea",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#fdf9f3",
        "primary-container": "#9E6E00",
        "secondary": "#a23d26",
        "on-surface-variant": "#504838",
        "tertiary-fixed": "#FFECC8",
        "surface-container-low": "#f7f3ed",
        "secondary-fixed-dim": "#ffb4a3",
        "on-surface": "#1c1c18",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#F0D07A",
        "surface-variant": "#EDE8DE",
        "on-tertiary-container": "#FFECC8",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ddd9d4",
        "outline": "#8A7A60",
        "surface-tint": "#9E6E00",
        "on-tertiary-fixed": "#251900",
        "on-secondary-container": "#731b07",
        "on-primary-fixed-variant": "#5E3D00",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#3d0600",
        "inverse-surface": "#31302d",
        "surface-container-high": "#ebe8e2",
        "surface": "#fdf9f3",
        "primary-fixed-dim": "#F5C43A",
        "on-secondary-fixed-variant": "#822611",
        "inverse-primary": "#F5C43A",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#FFDEA0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "container-max": "1200px",
        "unit": "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["DM Sans", "sans-serif"],
        "label-sm": ["DM Sans", "sans-serif"],
        "headline-lg": ["Fraunces", "serif"],
        "display-xl": ["Fraunces", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "headline-md": ["Fraunces", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};